apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  selector:
    app.kubernetes.io/name: swfactory
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
